name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонирует репозиторий

      - name: Change directory to family-time-backend
        run: |
          ls
          cd ./server/family-time-backend/
          docker-compose down

      - name: Up docker
        run: |
          ls
          cd ./server/family-time-backend/
          docker-compose up --build
    