name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонирует репозиторий

      - name: Change directory to family-time-backend
        run: |
          docker compose down

      - name: Up docker
        run: |
          docker compose up --build -d
    