name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git pull
        run: |
          cd ./server/family-time-backend/
          git pull origin development

      - name: Down docker
        run: |
          cd ./server/family-time-backend/
          docker compose down
      - name: Up docker
        run: |
          cd ./server/family-time-backend/
          docker-compose up --build
    